### ISSUE TITLE
JSON to dotLottie

### ISSUE THREAD

**Issue by alihs** [dotlottie/player-component#1]
I am trying to convert lottie JSON to dotLottie, though the server seems to be down
https://dotlottie.io/resources/json-to-dotLottie/

Do we some node module available to do this locally?

**Comment by erreib** [comment]
The converter is accessible through a button on that page, however I had very mixed success converting .json files to .lottie. Some files convert as expected but most of the ones that I tried would not display when loaded into the dotlottie player. 

I'd love to use dotlottie on my projects but with the lack of updates and support on this repo make it seem like it might be best to stick to the normal lottie component for now.

**Comment by alihs** [comment]
I too ran issues with preComps but since i my site is animation oriented i am forcing myself to use dotLottie. Also @erreib the new plugin (https://lottiefiles.com/plugins/after-effects) does offer automatic generation of dotlottie files

**Comment by alihs** [comment]
This works fine now
