### ISSUE TITLE
Optimized lottie file

### ISSUE THREAD

**Issue by Matteo-pd** [dotlottie/player-component#107]
I have an issue with displaying the Optimized dotLottie file. 
Normal, not optimized .lottie file is working.

I generated the files from Lottie's user panel.

Scripts:
```
https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.js
https://unpkg.com/@lottiefiles/lottie-interactivity@latest/dist/lottie-interactivity.min.js
```

My HTML:
`<dotlottie-player id="product-4-min" src="/dist/lottie/test-4-min.lottie"></dotlottie-player>
`

Error message in the console:
```
dotlottie-player.ts:688 Error: [dotLottie-player-component] TypeError: Cannot read properties of undefined (reading 'length')
    at createError (utils.ts:6:17)
    at dotlottie-player.ts:332:15
    at async DotLottiePlayer_1._fetchDotLottie (dotlottie-player.ts:336:5)
    at async DotLottiePlayer_1._fetchFileAndLoad (dotlottie-player.ts:398:56)
    at async DotLottiePlayer_1.load (dotlottie-player.ts:622:9)
    at async DotLottiePlayer_1.firstUpdated (dotlottie-player.ts:1068:14)
```

**Comment by Matteo-pd** [comment]
Hi @samuelOsborne,

it works from the Asset link. 
Also when I download the file from the Asset link it works.

**Comment by samuelOsborne** [comment]
@Matteo-pd So where did you get the original non working optimized file from? Which page was it? cheers

**Comment by Matteo-pd** [comment]
It was the "Download & Export section":

![image](https://github.com/dotlottie/player-component/assets/135317660/213dbdd6-ac93-4831-a58f-022e680da62e)

**Comment by samuelOsborne** [comment]
@Matteo-pd Thanks, is very helpful, if you're able to zip together the two files and link them here, working and not working it would help greatly find what the problem is

If github doesnt allow it, you can reach me at sam@lottiefiles.com

Cheers!
