### ISSUE TITLE
renderer="canvas" resulting in an error

### ISSUE THREAD

**Issue by katerlouis** [dotlottie/player-component#12]
I'm using the following in my nuxt project:

```html
<dotlottie-player
  src="https://assets2.lottiefiles.com/dotlotties/dlf10_l12sw9oo.lottie"
  autoplay
  renderer="canvas"
  loop
/>
```

Is it not possible to use other renderers than SVG with dotlottie? Or does the `.lottie`-file need to be prepared in a special way?

![image](https://user-images.githubusercontent.com/1983382/113110729-b1c77f80-9207-11eb-8d4f-998f0c4fcebb.png)
![image](https://user-images.githubusercontent.com/1983382/113110742-b5f39d00-9207-11eb-8136-38eddd4f66d5.png)

**Comment by johanaarstein** [comment]
I've made [a fork](https://github.com/johanaarstein/dotlottie-player) that adresses this issue. 😇

**Comment by samuelOsborne** [comment]
hi @katerlouis you can change renderer with v1.4.0
