### ISSUE TITLE
Found the vulnerability in the fflate

### ISSUE THREAD

**Issue by roylo-dd** [dotlottie/player-component#147]
I got the security report and found the vulnerability of dependency in the jszip of fflate

should I ignore this issue?

![image-20230614-022920](https://github.com/dotlottie/player-component/assets/83576885/77c20e58-f4ca-4912-b084-a068b104faca)

**Comment by samuelOsborne** [comment]
hi @roylo-dd Is this with jszip or fflate ?

**Comment by theashraf** [comment]
resolved in the latest dotlottie-js [release](https://github.com/dotlottie/dotlottie-js/releases/tag/%40dotlottie%2Fdotlottie-js%400.6.2)
