### ISSUE TITLE
Pausing animations after 1 loop

### ISSUE THREAD

**Issue by Saswat689** [dotlottie/player-component#159]
I have a simple lottie animation which I want to pause after it has looped once. I tried removing the loop prop but that removes the entire animation after 1 loop. Can anyone please help me out here ?

### What I want to achieve

An animation that completes one loop and stops at its last frame, meaning user does not keep seeing a looped animation

**Comment by samuelOsborne** [comment]
hi @Saswat689 you can set the loop prop to the number of loops you'd like it to do so:

```
<dotlottie-player id="player" src=".." autoplay loop=1></dotlottie-player>
```

Then in js / ts to make it stop at the last frame:

```
const player = document.getElementById("player");

player.addEventListener('complete', () => {
  const data = player.getLottie();

  if (data) {
    data.goToAndStop(data.totalFrames, true);
  }
})

```

**Comment by Saswat689** [comment]
@samuelOsborne Hi samuel, thank you for your prompt response. Can you provide me with a code sample specific to nextjs/react
