### ISSUE TITLE
Got Uncaught TypeError: (0 , import_react3.useSyncExternalStore) is not a function

### ISSUE THREAD

**Issue by karthest** [dotlottie/player-component#167]
Node :  v14.17.2
React : v17.0.2
Code : 
```tsx
import React from 'react'
import './index.scss'
import DotLottie from './assets/lottie/full/data.lottie?url'
import { DotLottiePlayer, Controls } from '@dotlottie/react-player';
import '@dotlottie/react-player/dist/index.css';

const App = (): JSX.Element => {

  return (
    <>
      <DotLottiePlayer
        src={DotLottie}
        autoplay
        loop
      >
        <Controls></Controls>
      </DotLottiePlayer>
    </>
  )
}

export default App 
```
Got this error:
<img width="1070" alt="image" src="https://github.com/dotlottie/player-component/assets/41997680/d9e5d76a-839c-41d6-919a-890297ed78f4">
and the lottie animation didn't show as expect.

**Comment by afsalz** [comment]
@karthest, Thank you for your interest in our react-player.

Currently, our react-player is designed to support React version 18 and above. As a result, features like useSyncExternalStore are implemented specifically for React 18.

We recommend using our [player-component](https://www.npmjs.com/package/@dotlottie/player-component) for older versions of React.

**Comment by karthest** [comment]
Thanks for your explaination. player-component works great.

**Comment by karthest** [comment]
Another question : Is there a way to pack lottie json file and required images into a dotlottie file ? Or how to deal with assets ?

**Comment by afsalz** [comment]
@karthest Yes, packing assets within `.lottie` is possible. Our [dotlottie-js](https://github.com/dotlottie/dotlottie-js) library may help with your use case. Also, please refer to [dotlottie structure](https://dotlottie.io/structure/#dotlottie-structure) to learn more about the dotlottie structure.

**Comment by karthest** [comment]
Thanks a lot
