### ISSUE TITLE
Use of eval in "node_modules/@dotlottie/player-component/dist/dotlottie-player.esm.js" is strongly discouraged as it poses security risks and may cause issues with minification

### ISSUE THREAD

**Issue by jpengelbrecht** [dotlottie/player-component#190]
Hi i see i get this warning in my build step when using this library.  so just a heads up

**Comment by samuelOsborne** [comment]
hi @jpengelbrecht Thanks, we're aware of this. Due to [lottie-web](https://github.com/airbnb/lottie-web) using eval for expression use, this warning will appear.
