### ISSUE TITLE
[react-player] `setAutoplay() Can't use whilst loading.` warning in console

### ISSUE THREAD

**Issue by ghtea** [dotlottie/player-component#214]
When I use `<DotLottiePlayer src="..." />` from `@dotlottie/react-player`,
I get `setAutoplay() Can't use whilst loading.` warning in console.
How can I fix this?

- codesandbox: https://codesandbox.io/s/lottie-warning-4g8fmj?file=/src/App.tsx
(the file is optimized .lottie)

**Comment by afsalz** [comment]
@ghtea thanks for bringing this up. we have added a fix for this https://github.com/dotlottie/player-component/pull/215. We will be releasing it as soon as possible

**Comment by afsalz** [comment]
Hi, @ghtea we just released a fix for this. Please try updating the player to the latest @dotlottie/react-player@1.4.2

**Comment by ghtea** [comment]
@afsalz thanks, warning disappeared!

**Comment by davidkhierl** [comment]
still happening on latest version

**Comment by ZainChen** [comment]
"@dotlottie/react-player": "^1.6.3":
<img width="367" alt="image" src="https://github.com/dotlottie/player-component/assets/15615524/310d73a6-3872-4a1f-8717-ea5c7223696f">

**Comment by afsalz** [comment]
Hello @sergio-milu We can't seem to reproduce this issue. Could you help us reproduce it in a codesandbox and share the link with us?

**Comment by sergio-milu** [comment]
> Hello @sergio-milu We can't seem to reproduce this issue. Could you help us reproduce it in a codesandbox and share the link with us?

Hey, i'm reproducing the issue when using NetxJs and dynamic import (lazy loading)

I think you can see it [here](https://codesandbox.io/p/devbox/mystifying-bogdan-5hf6gf?file=%2Fapp%2Fpage.tsx%3A19%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clps43jfj000a3b6i1yqieudw%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clps43jfi00023b6i8cwdrdm2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clps43jfi00073b6iv9kmdwd2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clps43jfi00093b6ikysjulad%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clps43jfi00023b6i8cwdrdm2%2522%253A%257B%2522id%2522%253A%2522clps43jfi00023b6i8cwdrdm2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clps4bsiy00023b6i3lkj6rwp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A19%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A19%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clps4bsiy00023b6i3lkj6rwp%2522%257D%252C%2522clps43jfi00093b6ikysjulad%2522%253A%257B%2522id%2522%253A%2522clps43jfi00093b6ikysjulad%2522%252C%2522activeTabId%2522%253A%2522clps4jlzy00n13b6i8tcfchmw%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3001%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clps4ho41009n3b6i8c7h0ula%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clps4jlzy00n13b6i8tcfchmw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clps43jfi00073b6iv9kmdwd2%2522%253A%257B%2522id%2522%253A%2522clps43jfi00073b6iv9kmdwd2%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clps47p9700so3b6i5sv9coaa%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clps47p9700so3b6i5sv9coaa%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by afsalz** [comment]
Hi @sergio-milu we have released a fix for this. Please let us know if you're still facing this issue with the new version `1.6.6`

**Comment by sergio-milu** [comment]
> Hi @sergio-milu we have released a fix for this. Please let us know if you're still facing this issue with the new version `1.6.6`

seems that is working now, thanks!
