### ISSUE TITLE
bug - [react-player] onEvent doesn't proc "complete" event

### ISSUE THREAD

**Issue by Mars-Interactive** [dotlottie/player-component#218]
Hi guys,

Reporting a small bug in "@dotlottie/react-player": "^1.4.0" :

after calling onEvent={eventHandler) and console logged the results for a noLooped animation:
I've received outputs of "ready" "frame" "play" events only
but **"complete" event didn't proc** at all

I've retested the animation with Loop=true, and the "loopComplete" procced as it should be
so, we are missing only the "complete" event

**Comment by afsalz** [comment]
Hi, @Mars-Interactive  we just released a fix for this. Please try updating the player to the latest @dotlottie/react-player@1.4.2
