### ISSUE TITLE
`loopComplete` event is not cleaned up

### ISSUE THREAD

**Issue by Il9** [dotlottie/player-component#239]
https://github.com/dotlottie/player-component/blob/c1d0f546132668a2d875da8230800a39eec6412d/packages/react-player/src/react-player.tsx#L217-L241

Because it does not return a cleanup that removes listening, the handler continues to be called even after the component is unmounted.
Am I using it wrong?

**Comment by theashraf** [comment]
@Il9 btw These are not DOM events, these are player specific events so it should be automatically cleared up from memory once the component is unmounted, as we destroy the player instance from memory on unmount. 

for clarification, can you show an example of the issue you're facing ? thanks!

**Comment by Il9** [comment]
@theashraf 
After unmounting, the ref is cleard, but the loopComplete event continues to be called.
In my case, I unmounted it through setState during onLoopComplete. However, even after that, the loop continued and the loopComplete handler continued to change the state.
<img width="511" alt="image" src="https://github.com/dotlottie/player-component/assets/19809942/de8b78eb-7309-427e-8c3c-ec9e02837229">

**Comment by Il9** [comment]
@theashraf 
I already tried it.
Now loopComplete is not continuously called, but it throws an error when it is finally unmounted.
It doesn't directly affect me, but I hope it gets fixed 

<img width="475" alt="image" src="https://github.com/dotlottie/player-component/assets/19809942/d565d842-5cd0-41ba-afa7-262cba0c8516">
<img width="499" alt="image" src="https://github.com/dotlottie/player-component/assets/19809942/60f1d76e-283c-43f0-8b13-c54d10cb84da">
<img width="499" alt="image" src="https://github.com/dotlottie/player-component/assets/19809942/59c31ade-5488-48d5-96f1-a37f97b0be8f">
<img width="506" alt="image" src="https://github.com/dotlottie/player-component/assets/19809942/5dabd3e0-0b6e-4762-8a67-0e3c4d843ee5">

**Comment by Xeneural** [comment]
> @theashraf I already tried it. Now loopComplete is not continuously called, but it throws an error when it is finally unmounted. It doesn't directly affect me, but I hope it gets fixed
> 
> <img alt="image" width="475" src="https://user-images.githubusercontent.com/19809942/270627663-d565d842-5cd0-41ba-afa7-262cba0c8516.png"> <img alt="image" width="499" src="https://user-images.githubusercontent.com/19809942/270627690-60f1d76e-283c-43f0-8b13-c54d10cb84da.png"> <img alt="image" width="499" src="https://user-images.githubusercontent.com/19809942/270627714-59c31ade-5488-48d5-96f1-a37f97b0be8f.png"> <img alt="image" width="506" src="https://user-images.githubusercontent.com/19809942/270627730-5dabd3e0-0b6e-4762-8a67-0e3c4d843ee5.png">

Hello, 

for the record: The same is happening to me on "@dotlottie/react-player": " 1.6.0"
