### ISSUE TITLE
web worker functionality is not documented

### ISSUE THREAD

**Issue by dhruv-tech** [dotlottie/player-component#247]
Came across the `worker` property while looking through `dotlottie-player.ts` in version 2.7.0.

This is an incredibly useful feature (thread blocking no more!) and I thank you pushing it.

It is so useful that it deserved a special announcement 😂

But hasn't been documented anywhere...

Therefore, requesting for the feature to be documented 🙏

**Comment by samuelOsborne** [comment]
Thanks @dhruv-tech, done 👍
