### ISSUE TITLE
Couldn't find package "@dotlottie/common@^0.7.1"

### ISSUE THREAD

**Issue by ronneldavis** [dotlottie/player-component#250]
Trying to install the latest version of @dotlottie/react-player@1.6.2 throws an error saying @dotlottie/common cannot be found on npm

**Comment by brianmorin-ef** [comment]
Also seeing this. Downgrading fixes

**Comment by guidodinello** [comment]
Same issue using yarn:
`
❯ yarn add @dotlottie/react-player
yarn add v1.22.19
[1/4] Resolving packages...
error Couldn't find package "@dotlottie/common@^0.7.1" required by "@dotlottie/react-player" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`
❯ yarn --version
1.22.19

**Comment by jwhitmarsh** [comment]
@afsalz sorry to comment on a closed issue, but this is also affecting `@dotlottie/player-component` (i'm using it in a SolidJS application with TypeScript) - I can see you've released `@dotlottie/react` with this fix, is there a chance you could also release `player-component`?

**Comment by theashraf** [comment]
@jwhitmarsh Please check out the latest @dotlottie/react-player and @dotlottie/player-component release, and let us know if you're still facing the same issue
