### ISSUE TITLE
No exported type 'DotLottieRefProps'

### ISSUE THREAD

**Issue by adelegard** [dotlottie/player-component#255]
The readme [here](https://github.com/dotlottie/player-component/tree/master/packages/react-player) calls out using `DotLottieRefProps` (from `@dotlottie/react-player`), however that is no longer exported from the package. It was on the version 1.1.0.

**Comment by kuku1234us** [comment]
It's been secretly changed to AnimationItem....

```import { DotLottiePlayer, AnimationItem } from "@dotlottie/react-player";
  ...
  const myRef = useRef<AnimationItem>(null);
  ...
  const handleClick = () => {
    if (!myRef.current) return;
    myRef.current.goToAndPlay(0);
  };
  ...
  return <DotLottiePlayer
        src="/whatever/MyAnimation.lottie"
        autoplay={false} loop={false}
        ref={myRef}
      />;
```

Works for me in version "^1.6.3"  Future and past versions not guaranteed.

**Comment by adelegard** [comment]
> It's been secretly changed to AnimationItem....
> 
> ```
>   ...
>   const myRef = useRef<AnimationItem>(null);
>   ...
>   const handleClick = () => {
>     if (!myRef.current) return;
>     myRef.current.goToAndPlay(0);
>   };
>   ...
>   return <DotLottiePlayer
>         src="/whatever/MyAnimation.lottie"
>         autoplay={false} loop={false}
>         ref={myRef}
>       />;
> ```
> 
> Works for me in version "^1.6.3" Future and past versions not guaranteed.

Ah! Beautiful. That does the trick indeed. Thank you!

**Comment by theashraf** [comment]
Please review the `player.tsx` component in the dotLottie Playground for an example of its implementation. It has been updated to the from `DotLottieRefProps` to `DotLottieCommonPlayer`, which you can find at: https://github.com/dotlottie/player-component/blob/master/apps/dotlottie-playground/src/components/player.tsx#L18

We apologize for any inconvenience caused by these breaking changes. We will soon be updating the documentation and READMEs to reflect these updates.

**Comment by EvHaus** [comment]
Hmm, the code in that example still isn't passing TS checks for me. I'm getting:

```ts
myComponent.tsx:76:9 - error TS2322: Type 'MutableRefObject<DotLottieCommonPlayer | undefined>' is not assignable to type 'Ref<DotLottieCommonPlayer | null> | undefined'.
  Type 'MutableRefObject<DotLottieCommonPlayer | undefined>' is not assignable to type 'RefObject<DotLottieCommonPlayer | null>'.
    Types of property 'current' are incompatible.
      Type 'DotLottieCommonPlayer | undefined' is not assignable to type 'DotLottieCommonPlayer | null'.
        Type 'undefined' is not assignable to type 'DotLottieCommonPlayer | null'.

76         ref={lottieRef}
           ~~~

  node_modules/.pnpm/@types+react@18.2.37/node_modules/@types/react/index.d.ts:119:9
    119         ref?: Ref<T> | undefined;
                ~~~
    The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & Props & RefAttributes<DotLottieCommonPlayer | null>'
```

Had to change `const lottiePlayer = useRef<DotLottieCommonPlayer>();` to `const lottiePlayer = useRef<DotLottieCommonPlayer>(null);`
