### ISSUE TITLE
structuredClone is not defined

### ISSUE THREAD

**Issue by joyboy1200** [dotlottie/player-component#256]
Hey,

I see that `getMockDotLottieState` function in `apps/dotlottie-playground/src/utils.ts` file and `updateSrc` function in `packages/common/src/dotlottie-player.ts` are using the `structuredClone` function which is not available for chrome versions < 98 [ref](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility), which is making the updated version incompatible with those versions. I can do a PR to convert those to `Object.assign` function or any other method to replace `structuredClone`.

Thanks

**Comment by theashraf** [comment]
Hey @joyboy1200 

Great catch! Yes, a PR to fix this would be awesome. Go for it.

Thanks!
