### ISSUE TITLE
Is there any way to run this library in a lower node version i have 14 and it fails to install 

### ISSUE THREAD

**Issue by Ornaldo-RP-R** [dotlottie/player-component#267]

**Comment by tejavenkatsgrft** [comment]
I am using node version 16.x. The module `@dotlottie/common@0.7.3` requires node version > 18. Can any one fix this? Or help with a work around

**Comment by theashraf** [comment]
@Ornaldo-RP-R, @tejavenkatsgrft, if upgrading to node@18 isn't possible for you, then you might need to attempt the installation with this command: `npm install @dotlottie/react-player --ignore-engines`
