### ISSUE TITLE
Warning: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by mjyoung** [dotlottie/player-component#273]
Using `@dotlottie/react-player` `1.6.6` and NextJS. 

I have a loading spinner as 
```tsx
import { DotLottiePlayer, PlayMode } from '@dotlottie/react-player';

import json from './LoadingSpinner.json';

export default function LoadingSpinnerComponent() {
  return (
    <div className="absolute left-0 top-0 h-full w-full center">
      <DotLottiePlayer
        className="z-50"
        autoplay
        loop
        playMode={PlayMode.Normal}
        src={json}
        style={{ height: '300px', width: '300px' }}
      ></DotLottiePlayer>
    </div>
  );
}
```

In my `_app.tsx` I have:
```tsx
          <Suspense fallback={<LoadingSpinner />}>
```

I get the following error: 

`Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
`

**Comment by theashraf** [comment]
@mjyoung Which nextjs version you're using ?
