### ISSUE TITLE
Making responsive lotties

### ISSUE THREAD

**Issue by sergio-milu** [dotlottie/player-component#278]
Hi,

I was trying to make some lotties responsive to the container, but I have an issue this [this inner div](https://github.com/dotlottie/player-component/blob/e38f3b6e57500bbf86f53c928d58854cd218a2cf/packages/react-player/src/react-player.tsx#L299),

could it be possible to add a prop to modify this styles and add more? I need height: 100% and width : 100% here too.

Thanks

**Comment by afsalz** [comment]
@sergio-milu This is expected if you're not importing the index.css file. 

We have just pushed a PR to add `height: 100%, width: 100%` to .animation div. This would allow to use the react-player without the css files. 
However if you wanna use Controls component you would still need to import the css file.

Please wait for our next release and help us verify if this solves the issue.

**Comment by afsalz** [comment]
@sergio-milu We have just release the fix. Latest version --> @dotlottie/react-player@1.6.9 

Feel free reopen the issue, if the issue still persists.
