### ISSUE TITLE
loopComplete event does not fire after first cycle if direction is -1

### ISSUE THREAD

**Issue by ishuvalov** [dotlottie/player-component#291]
When playback direction is set to `-1` the `loopComplete` event is not fired after the first loop cycle. After the second cycle events are fired normally.
https://codesandbox.io/p/sandbox/elegant-dawn-yls6wm?file=%2Fsrc%2FApp.js

UPD: This bug also seems to have a side effect: When direction is `-1` the player plays 1 extra loop for number set in options.
This snippet plays 3 loops
```js
<DotLottiePlayer src="..." direction={-1} loop={2} />
```

**Comment by afsalz** [comment]
hi @ishuvalov we just released a fix for this. Please update to latest version of react and try it `@dotlottie/react-player@1.6.13` 

Let us know if you're still facing  this issue.

**Comment by ishuvalov** [comment]
@afsalz Thank you very much for the quick patch and for the great player! 
Unfortunately, upgrading to `1.16.13` introduced new odd bug: If direction set to `-1` the `stop()` method does not work after `playSegments()` was called. 

Here is the updated sandbox https://codesandbox.io/p/sandbox/elegant-dawn-forked-kx8g4w?file=%2Fsrc%2FApp.js%3A21%2C38
Please note if you change version of `@dotlottie/react-player` to `1.16.12` in `package.json` this bug disappears.
Thanks!

**Comment by afsalz** [comment]
Hi @ishuvalov thanks for pointing this out. we just triggered a new release. It will take few minutes to be available. Please get back to us if you face these issues in `@dotlottie/react-player@1.6.14`

**Comment by ishuvalov** [comment]
@afsalz All works fine. Thank you for your help! 👏

**Comment by ishuvalov** [comment]
@afsalz Thank you for all your efforts on fixing this. I've found that the bug with loop count is still present if `playSegments()` is used. In this case the first `loopComplete` event is missed like in the original issue description above.
Here is the codesandbox https://codesandbox.io/p/sandbox/elegant-dawn-forked-6w38g9?file=%2Fsrc%2FApp.js%3A20%2C1
Click the play button and look on the loop counter.
