### ISSUE TITLE
Player can go beyond the frame range

### ISSUE THREAD

**Issue by ishuvalov** [dotlottie/player-component#292]
On some animations player is stopped on the frame just after the actual last animation frame. Which leads to the empty player.

For example in this animation https://lottiefiles.com/animations/infinity-loading-blue-A8cLWc9JCH
Total animation frames: 28
The last frame to play: totalFrames - 1 = 27

If you visit the animation page using the link above and turn off the loop setting you see that the player stops on the right last frame (27) somehow (probably this case is specially handled on the web site), but the timeline still shows that there is one more frame and you can drag the seeker on it manually.
If you programmatically use dotlottie player with such animation, it stops on that false last frame.

I believe this is related to https://github.com/dotlottie/player-component/issues/281

**Comment by ishuvalov** [comment]
UPD: You can see the empty last frame effect in this sandbox 
https://codesandbox.io/p/sandbox/elegant-dawn-forked-qdlwkf?file=%2Fsrc%2FApp.js%3A1%2C1

**Comment by Hamdysaad20** [comment]
@ishuvalov  you need to add loop attribute to it as following:
```
const App = () => {
  return (
    <div>
      <DotLottiePlayer
        src="https://assets-v2.lottiefiles.com/a/3a76f9ac-731d-11ee-9d1c-afe05e840fee/c9TxQnho2e.lottie"
        autoplay
        loop
        speed={0.5}
      >
        <Controls />
      </DotLottiePlayer>
    </div>
  );
};

```

**Comment by ishuvalov** [comment]
@Hamdysaad20 Thanks for the advice! You're right. If the `loop` setting is `on` there is no problem with empty frame. But I need just a single time play not loop, and still it ends with the empty frame because player finishes on non-existing frame - the one just after the actual last frame in animation.

**Comment by timo-bes** [comment]
We are experiencing the same issue. Will there be an update for this issue?
