### ISSUE TITLE
window not defined using NextJS

### ISSUE THREAD

**Issue by RedBaronKU** [dotlottie/player-component#46]
When using lottie-player to load your *.lottie file, This error pops up in NextJS

ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///Users/kumarutkarsh/Documents/app-store/frontend/web/node_modules/@dotlottie/player-component/dist/dotlottie-player.js (25:25)
<unknown>
file:///Users/kumarutkarsh/Documents/app-store/frontend/web/node_modules/@dotlottie/player-component/dist/dotlottie-player.js (1:69)
Object.<anonymous>
file:///Users/kumarutkarsh/Documents/app-store/frontend/web/node_modules/@dotlottie/player-component/dist/dotlottie-player.js (1:220)
Module._compile
node:internal/modules/cjs/loader (1105:14)
Module._extensions..js
node:internal/modules/cjs/loader (1159:10)

**Comment by samuelOsborne** [comment]
Thanks for creating this issue, will check it out.

**Comment by samuelOsborne** [comment]
@RedBaronKU I'll add a check if window is defined, but as this concerns animations running on the front-end it would also be best for you to set it up on nuxt to run animations only on the front end.

**Comment by chris-calo** [comment]
@RedBaronKU @samuelOsborne It looks like this is being trigged by [Lit's](https://lit.dev/) (a core web component dependency of this package) aggressive usage of `window` as a result of its ShadyCSS polyfill (see below screenshot pulled from `/dist/dotlottie-player.js`. Unless Lit (and/or its subsequent dependencies) support a way of disabling this… somewhat overkill… polyfilling, I fear it would require a fairly dramatic re-write here in order to implement proper support and drop Lit entirely.

It appears to be too far up the callstack to be snuffed out via "conventional" means (e.g. – `window !== "undefined"` checks, or similar) or Next.js-specific bandaids (e.g. – `next/dynamic` → `{ ssr: false }` calls), at least based on my cursory attempts.

<img width="708" alt="Bildschirmfoto 2022-09-16 um 22 24 58" src="https://user-images.githubusercontent.com/3837103/190836874-767b33a3-4864-4e8b-a314-5a9fc9ad5415.png">

> **Source:** I'm having the same issue when trying to use `@dotlottie/player-component` with Next.js server-side.

**Comment by chris-calo** [comment]
Not particularly familiar with Rollup (which is what this package is using for a build system), however [Lit has documentation on polyfill usage.](https://lit.dev/docs/tools/requirements/) Seems like the logical place to start.

**Comment by johanaarstein** [comment]
You may have figured this out already, but in Next this is solved by importing the module in an useEffect hook.

**Comment by mimiqkz** [comment]
I just did 
```
useEffect(() => {
  import("@dotlottie/player-component")
}, [])
```

**Comment by philippeh-mf** [comment]
Hi,
Did anyone manage to use the `useEffect` solution with a  a production build (`npm run build && npm run start`) ?

I'm getting this error in run time when my app is rendering the player:
**Uncaught (in promise) ChunkLoadError: Loading chunk 386 failed.**

It works fine in dev mode though.

**Comment by johanaarstein** [comment]
There appears to be a bug in either Next 13, somewhere in the package, or both. After build one variable in the package gets declared twice, causing function to break. It seems like a minification error, but idk. The only sollution I've found that works so far is to downgrade to Next 12.

**Comment by philippeh-mf** [comment]
I'm already on Next 12. 
Maybe it has something to do with my Next config.
@johanaarstein would you share your `next.config.js` file?

**Comment by philippeh-mf** [comment]
SWC was indeed my issue. Thanks!

**Comment by EtienneExalgo** [comment]
@chris-calo You could do that this way to use NextJS Dynamic import :

```
const DynamicLottie = dynamic(() => import('../lottiePlayer'), {
    loading: () => 'Loading...',
    ssr: false,
})
const Acomponent = ({ }) => {
   return <DynamicLottie src={"whatever"} alt={"whatever"t} />
}
```

And put your Lottie imports in a lottiePlayer.js : 
```
import '@dotlottie/player-component';

const Lottieplayer = ({ src,alt }) => {
        return (<dotlottie-player
            src={src}
            autoplay={false}
            loop={false}
            alt={alt}
        />);
}
export default Lottieplayer;
```

This is an alternative to @mimiqkz useEffect import... And it produce the same minifying bug corrected by @johanaarstein tip (swcMinify: false)

**Comment by zek** [comment]
Can we just check if window exists or not. 
If doesn't exists ignore the code block?

**Comment by woss** [comment]
this happens with the sveltekit with ssr enabled. 

Here is the working example how to use this lib with ssr
```svelte
<script lang="ts">
import { onMount } from 'svelte';

// props
export let src: string;
export let loop = true;
export let autoplay = true;

let extraClass = '';
export { extraClass as class };
onMount(async () => {
  await import('@dotlottie/player-component');
});
</script>

<dotlottie-player src="{src}" autoplay="{autoplay}" loop="{loop}" class="h-96 {extraClass}">
</dotlottie-player>
```

**Comment by MeltingOpera** [comment]
is there any solution that works with NextJS 13.4 yet?

**Comment by theashraf** [comment]
please use the react dotlottie player -> https://www.npmjs.com/package/@dotlottie/react-player
