### ISSUE TITLE
Does this library support react native?

### ISSUE THREAD

**Issue by thanhnvpk01168** [dotlottie/player-component#64]
I want to use dotlottie in react native but don't know if this library supports it

**Comment by samuelOsborne** [comment]
hey @thanhnvpk01168 you should be able to use dotlottie in react-native, I got it working here:

https://codesandbox.io/s/react-native-dotlottie-5y9qqz

**Comment by pooja-hcom** [comment]
@samuelOsborne this doesn't work in a real react native application. It throws an error saying `ReferenceError: Property 'HTMLElement' doesn't exist`.

**Comment by pooja-hcom** [comment]
@samuelOsborne this doesn't work in a real react native application. It throws an error saying `ReferenceError: Property 'HTMLElement' doesn't exist.`

**Comment by pooja-hcom** [comment]
Your example from codesandbox.io is using a package called `react-native-web` which i think allows rendering of HTML elements using a different engine React Native DOM, which is not used in a real react native applications.
