### ISSUE TITLE
Unable to use this library in React Native

### ISSUE THREAD

**Issue by pooja-hcom** [dotlottie/player-component#81]
I'm unable to use this library in my react native application. It throws an error saying `ReferenceError: Property 'HTMLElement' doesn't exist.`. Are we planning to add support for react native applications in it?

**Comment by samuelOsborne** [comment]
Hi @pooja-hcom We do, but its not on this or next quarters roadmap so will be a while

**Comment by theashraf** [comment]
@pooja-hcom This dotlottie player doesn't support React Native, better to have a look at https://github.com/lottie-react-native/lottie-react-native
