### ISSUE TITLE
Direct import support for nuxt3

### ISSUE THREAD

**Issue by jpengelbrecht** [dotlottie/player-component#85]
It would be nice if we could use this as a direct import in nuxt3,  plugins are added to every page on your website it isn't the performant choice.  And the whole point of this technology is performance.

Currently direct imports gives the error
` At least one <template> or <script> is required in a single file component.`

Even currently installed as a plugin it gets the warning.  `failed to resolve component: dotlottie-player`
which is supposedly fixed by adding it as a custom component in your complier options,  however this gives the same error as using it directly.
` At least one <template> or <script> is required in a single file component.`

so ideally it would be nice if the nuxt3 support would be re-evaluated

**Comment by samuelOsborne** [comment]
Thanks for your feedback @jpengelbrecht, we are currently evaluating our players and this is useful feedback for when we create a Vue wrapper.

Are you currently able to get this player working for nuxt3 in the mean time?

**Comment by jpengelbrecht** [comment]
@samuelOsborne yea it actually works pretty nice.   it just gives a warning 
![image](https://user-images.githubusercontent.com/93583336/232740627-d74cfae5-08a3-47ac-8e87-ecfeb53b1254.png)

**Comment by samuelOsborne** [comment]
@jpengelbrecht Are you able to get rid of the warning by excluding it as it says?

**Comment by AndersNielsen85** [comment]
@jpengelbrecht @samuelOsborne 
The warning can be suppressed with
```
export default defineNuxtConfig({
  vue: {
    compilerOptions: {
      isCustomElement: (tag) => tag.startsWith('dotlottie'),
    },
  },
});
```

It would be really nice to be able to do a direct import though, rather than having to add it globally :)

**Comment by samuelOsborne** [comment]
Thanks @AndersNielsen85, Yes that would be ideal, we're working on adding player support for the various frameworks so hopefully that'll solve this issue :-)
