### ISSUE TITLE
Add animationData as property

### ISSUE THREAD

**Issue by gtolarc** [dotlottie/player-component#88]
For performance reasons, I'd like to load the dotLottie files in advance and use them immediately when needed.
For now, there doesn't seem to be a workaround other than to hide dotlottie-player before use.

https://github.com/dotlottie/player-component/blob/master/src/dotlottie-player.ts#L47
https://github.com/dotlottie/player-component/blob/master/src/dotlottie-player.ts#L318

If there is an animationData property, I think we could use the fetchPath function to fetch it in advance and use it when we want, is it possible to add this feature?

**Comment by samuelOsborne** [comment]
@gtolarc If you're fetching the dotLotties yourself, you could do something like this:

```
<Fetch files etc...>
        if (playerRef.current) {
          playerRef.current.load(animationData);
        }
        
        
        return({
                {lottieData && (
            <dotlottie-player
              ref={playerRef}
              autoplay
              loop
            >
            </dotlottie-player>
        )
        }
    })
```

**Comment by gtolarc** [comment]
> 
I know the way you're talking about from the documentation.

I want to do preloading without the dotlottie-player DOM being present, so it would be really useful to be able to take animationData as an property, what do you think?

**Comment by gtolarc** [comment]
I misunderstood what you said. I've verified that it works. @samuelOsborne
