### ISSUE TITLE
Intermission property has no effect

### ISSUE THREAD

**Issue by sergeykcommpeak** [dotlottie/player-component#91]
It seems like intermission attribute does nothing. The player starts the next loop immediately. 
My code is pretty straightforward: 
`<dotlottie-player ref={player} intermission={9} autoplay loop  />`
Actual lottie is loaded to this player later via `player.load()`

Am I missing smth or is it a bug? 
Thanks!

**Comment by samuelOsborne** [comment]
Will look in to this @sergeykcommpeak in the meanwhile, because you're manually loading via load() you can add a setTimeout to that call

**Comment by samuelOsborne** [comment]
hi @sergeykcommpeak its actually because the intermission is in milliseconds, try out intermission={9000} should work

**Comment by sergeykcommpeak** [comment]
@samuelOsborne Thanks, it does work. Sorry I haven't figured it out myself.
